### ISSUE TITLE
Recommend repo

### ISSUE THREAD

**Issue by WoodSugar** [jwwthu/GNN4Traffic#6]
Dear weiwei,
        
Thank you for maintaining this good repo.
        
I recommend my repo as a uesful reference in this community: [Paper Link](https://www.sciencedirect.com/science/article/abs/pii/S1566253524000198). 

Codes are also open-sourced : [Codes](https://github.com/WoodSugar/PreSTNet).

Thank you.

**Comment by jwwthu** [comment]
Sure, I would add it. Thanks!
