### ISSUE TITLE
A Dynamic Bernstein Graph Recurrent Network for Wireless Cellular Traffic Prediction

### ISSUE THREAD

**Issue by Ali-Meh619** [jwwthu/GNN4Traffic#7]
Hi again @jwwthu,
 
I would appreciate it if you can add my IEEE ICC 2023 paper to your github repository. Here is the link.
https://ieeexplore.ieee.org/document/10279102

It is for last year but still useful and an innovative GNN method.
Thank you very much.
Best,
Ali

**Comment by jwwthu** [comment]
This project focuses on road traffic prediction and Wireless Cellular Traffic Prediction is not a good fit.
